package DataMiningGUI;

import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Beza
 */
public class CreateEditPatientProfile extends javax.swing.JFrame {

    private Object event;

    public String PatientName = "Patient Name";
    public String PatientID = "#";
    public String DOB = "mm/ddyyyy";
    public String Age = "00";
    public String Gender = "Female/Male";
    public String Weight = "000";
    

    public void setPatientName(String PatientName) {
        this.PatientName = PatientName;
    }

    public void setAge(String Age) {
        this.Age = Age;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public void setWeight(String Weight) {
        this.Weight = Weight;
    }


    

    /**
     * Creates new form CreateEditPatientProfile
     */
    public CreateEditPatientProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBoxPatientName = new javax.swing.JTextField();
        txtBoxAge = new javax.swing.JTextField();
        txtBoxGender = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaPatientHistory = new javax.swing.JTextArea();
        lblPatientHistory = new javax.swing.JLabel();
        lblPatientDrugHistory = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        btnSaveChanges = new javax.swing.JButton();
        buttonDone = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        txtBoxWeight = new javax.swing.JTextField();
        txtBoxPatientID = new javax.swing.JTextField();
        lblFullName1 = new javax.swing.JLabel();
        txtBoxDOB = new javax.swing.JTextField();
        lblDOB1 = new javax.swing.JLabel();
        lblWeight1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePatientDrugHistory = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBoxPatientName.setText("Patient Name");
        txtBoxPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxPatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtBoxPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 110, 136, -1));
        txtBoxPatientName.getAccessibleContext().setAccessibleName("");

        txtBoxAge.setText("00");
        getContentPane().add(txtBoxAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 148, 84, -1));

        txtBoxGender.setText("F");
        getContentPane().add(txtBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 186, 240, -1));

        txtAreaPatientHistory.setColumns(20);
        txtAreaPatientHistory.setRows(5);
        jScrollPane4.setViewportView(txtAreaPatientHistory);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 423, 470, 145));

        lblPatientHistory.setText("Diagnosis:");
        getContentPane().add(lblPatientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, -1, -1));

        lblPatientDrugHistory.setText("Patient Drug History:");
        getContentPane().add(lblPatientDrugHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, -1, -1));

        lblFullName.setText("ID:");
        getContentPane().add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 113, -1, -1));

        lblDOB.setText("Age:");
        getContentPane().add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        lblGender.setText("Gender:");
        getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        lblWeight.setText("Weight:");
        getContentPane().add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 54));

        buttonDone.setText("Done");
        buttonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoneActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 54));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, 440, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataMiningGUI/symbol.png"))); // NOI18N
        jLabel1.setName("imageContainer"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 170));

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 71, 53));

        txtBoxWeight.setText("000");
        txtBoxWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxWeightActionPerformed(evt);
            }
        });
        getContentPane().add(txtBoxWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 224, 206, -1));

        txtBoxPatientID.setText("#");
        txtBoxPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxPatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtBoxPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 110, 65, -1));

        lblFullName1.setText("Full Name:");
        getContentPane().add(lblFullName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 113, -1, -1));

        txtBoxDOB.setText("mm/dd/yyyy");
        getContentPane().add(txtBoxDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 148, 92, -1));

        lblDOB1.setText("  DOB:");
        getContentPane().add(lblDOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 151, -1, -1));

        lblWeight1.setText("KG");
        getContentPane().add(lblWeight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 227, -1, -1));

        tablePatientDrugHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drugs", "Dosage", "Start", "Stop"
            }
        ));
        jScrollPane3.setViewportView(tablePatientDrugHistory);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 287, 470, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getValues(List myList) {
        System.out.println(myList);
    }
    private void txtBoxPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxPatientNameActionPerformed

    @SuppressWarnings("deprecation")
    private void buttonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoneActionPerformed
        // TODO add your handling code here:
       // System.out.println(haschanges());
        if(Changed()) {
            JOptionPane.showMessageDialog(null, "Please select 'save changes' or 'cancel'", "Changes not saved", JOptionPane.WARNING_MESSAGE);
        } else {
            JFrame home = new Home();
            home.show();
            this.hide();
        }
    }//GEN-LAST:event_buttonDoneActionPerformed

    @SuppressWarnings("deprecation")
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        JFrame home = new Home();
        home.show();
        this.hide();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
                                                       
        //Updating entry in database
        Connection conn = JdbcConnection.GetConnection();
        ResultSet SetFromTable = null;
        
        try {
            String query = "Insert into PATIENT(PTNAME, PTID, PTAGE, PTSEX, PTWEIGHT) values(?,?,?,?,?)";
            
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, txtBoxPatientName.getText());
            pst.setString(2, txtBoxPatientID.getText());
            pst.setString(3, txtBoxAge.getText());
            pst.setString(4, txtBoxGender.getText());
            pst.setString(5, txtBoxWeight.getText());
            pst.execute();
                    
            JOptionPane.showMessageDialog(null,"Saved");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void txtBoxPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxPatientIDActionPerformed

    private void txtBoxWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxWeightActionPerformed
    private boolean Changed() {
        //return TRUE if the values changed

        return !(CreateEditPatientProfile.txtBoxPatientName.getText().equals(PatientName)
                && this.txtBoxPatientID.getText().equals(PatientID)           
                && this.txtBoxDOB.getText().equals(DOB)
                && this.txtBoxAge.getText().equals(Age)
                && this.txtBoxGender.getText().equals(Gender)
                && this.txtBoxWeight.getText().equals(Weight)
               );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEditPatientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEditPatientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEditPatientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEditPatientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEditPatientProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblFullName1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPatientDrugHistory;
    private javax.swing.JLabel lblPatientHistory;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeight1;
    public static javax.swing.JTable tablePatientDrugHistory;
    public javax.swing.JTextArea txtAreaPatientHistory;
    public static javax.swing.JTextField txtBoxAge;
    public javax.swing.JTextField txtBoxDOB;
    public static javax.swing.JTextField txtBoxGender;
    public static javax.swing.JTextField txtBoxPatientID;
    public static javax.swing.JTextField txtBoxPatientName;
    public static javax.swing.JTextField txtBoxWeight;
    // End of variables declaration//GEN-END:variables
}
